'use strict';
// @must-b/pack-system — auto-generated by scripts/build-packs.mjs
// Extensions: memory-lancedb, memory-core, acpx, diffs, diagnostics-otel, voice-call, open-prose, lobster, ollama, sglang, vllm, llm-task, copilot-proxy, google-gemini-cli-auth, minimax-portal-auth

try { require('./extensions/memory-lancedb/index.cjs'); } catch(e) { console.warn('[pack-system] memory-lancedb load error:', e.message); }
try { require('./extensions/memory-core/index.cjs'); } catch(e) { console.warn('[pack-system] memory-core load error:', e.message); }
try { require('./extensions/acpx/index.cjs'); } catch(e) { console.warn('[pack-system] acpx load error:', e.message); }
try { require('./extensions/diffs/index.cjs'); } catch(e) { console.warn('[pack-system] diffs load error:', e.message); }
try { require('./extensions/diagnostics-otel/index.cjs'); } catch(e) { console.warn('[pack-system] diagnostics-otel load error:', e.message); }
try { require('./extensions/voice-call/index.cjs'); } catch(e) { console.warn('[pack-system] voice-call load error:', e.message); }
try { require('./extensions/open-prose/index.cjs'); } catch(e) { console.warn('[pack-system] open-prose load error:', e.message); }
try { require('./extensions/lobster/index.cjs'); } catch(e) { console.warn('[pack-system] lobster load error:', e.message); }
try { require('./extensions/ollama/index.cjs'); } catch(e) { console.warn('[pack-system] ollama load error:', e.message); }
try { require('./extensions/sglang/index.cjs'); } catch(e) { console.warn('[pack-system] sglang load error:', e.message); }
try { require('./extensions/vllm/index.cjs'); } catch(e) { console.warn('[pack-system] vllm load error:', e.message); }
try { require('./extensions/llm-task/index.cjs'); } catch(e) { console.warn('[pack-system] llm-task load error:', e.message); }
try { require('./extensions/copilot-proxy/index.cjs'); } catch(e) { console.warn('[pack-system] copilot-proxy load error:', e.message); }
try { require('./extensions/google-gemini-cli-auth/index.cjs'); } catch(e) { console.warn('[pack-system] google-gemini-cli-auth load error:', e.message); }
try { require('./extensions/minimax-portal-auth/index.cjs'); } catch(e) { console.warn('[pack-system] minimax-portal-auth load error:', e.message); }

module.exports = { packName: 'system', extensions: ["memory-lancedb","memory-core","acpx","diffs","diagnostics-otel","voice-call","open-prose","lobster","ollama","sglang","vllm","llm-task","copilot-proxy","google-gemini-cli-auth","minimax-portal-auth"] };